spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springboot
#    username: root
#    password: zjy123
#    driverClassName: com.mysql.jdbc.Driver
#    max-active: 20
#    max-idle: 8
#    min-idle: 8
#    initial-size: 10
  # Specify the DBMS
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
  # Naming strategy
  #[org.hibernate.cfg.ImprovedNamingStrategy
  #org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  # stripped before adding them to the entity manager)
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false # Enable template caching.
    encoding: UTF-8 # Template files encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    servlet.content-type: text/html # Content-Type value written to HTTP responses.
  mvc:
    static-path-pattern: /static/**

  redis:
  # Redis数据库索引（默认为0）
    database: 0
  # Redis服务器地址
    host: 192.168.157.128
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password:
  # 连接池最大连接数（使用负值表示没有限制）
    pool:
      jedis:
        max-active: 1000
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # 连接池中的最大空闲连接
        max-idle: 10
  # 连接池中的最小空闲连接
        min-idle: 0
  # 连接超时时间（毫秒）
    timeout: 1000
##sharding-jdbc 数据库配置
database0:
##数据库database0地址
  url: jdbc:mysql://localhost:3306/database0?characterEncoding=utf8&useSSL=false
##数据库database0用户名
  username: root
##数据库database0密码
  password: zjy123
##数据库database0驱动
  driverClassName: com.mysql.jdbc.Driver
##数据库database0名称
  databaseName: database0
database1:
  ##数据库database1地址
  url: jdbc:mysql://localhost:3306/database1?characterEncoding=utf8&useSSL=false
  ##数据库database1用户名
  username: root
  ##数据库database1密码
  password: zjy123
  ##数据库database1驱动
  driverClassName: com.mysql.jdbc.Driver
  ##数据库database1名称
  databaseName: database1
