spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: zjy123
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  # Specify the DBMS
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
  # Naming strategy
  #[org.hibernate.cfg.ImprovedNamingStrategy
  #org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  # stripped before adding them to the entity manager)
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false # Enable template caching.
    encoding: UTF-8 # Template files encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    servlet.content-type: text/html # Content-Type value written to HTTP responses.
  mvc:
    static-path-pattern: /static/**